[project]
name = "vasijas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.0",
    "diffusers[training]>=0.37.1",
    "docling>=2.88.0",
    "gdown>=6.0.0",
    "ipython>=9.13.0",
    "matplotlib>=3.10.9",
    "peft>=0.19.0",
    "pip>=26.1.1",
    "playwright>=1.51.0",
    "pre-commit>=4.6.0",
    "requests>=2.32.0",
    "torchmetrics[image]>=1.9.0",
    "torch==2.5.0"
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu121", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu121", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]