[project]
name = "vasijas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "beautifulsoup4",
    "diffusers[training]",
    "docling",
    "gdown",
    "ipython",
    "attrdict",
    "einops",
    "sentencepiece",
    "matplotlib",
    "peft",
    "pip",
    "playwright",
    "requests",
    "tiktoken",
    "torchmetrics[image]",
    "tensorflow",
]
